server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoint:
    health:
      show-details: when_authorized
    flowable:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
flowable:
  idm:
    password-encoder: spring_delegating
  rest:
    app:
      admin:
        user-id: admin
        password: admin
        first-name: admin
        last-name: admin